version: '3.8'
volumes:
  data:
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=esabapp
    command: --init-file /data/application/init.sql
    networks:
      - app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app
  mailserver:
    image: rnwood/smtp4dev:v3
    ports:
      - "3001:80"
      - "2525:25"
    networks:
      - app 
networks:
  app:
    driver: bridge
